# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySession',
        ),
    ]
